from abc import ABC, abstractmethod
from typing import List, Dict
from ..domain.entities import Order, ParamGroup, Inspection
class IOrderRepository(ABC):
    @abstractmethod
    def get_order(self, order_id:int) -> Order: ...
class IProductParamRepository(ABC):
    @abstractmethod
    def get_groups_for_product(self, product_code:str) -> List[ParamGroup]: ...
class IInspectionRepository(ABC):
    @abstractmethod
    def upsert_inspection(self, insp:Inspection) -> int: ...
    @abstractmethod
    def save_values(self, inspection_id:int, values:Dict[str,str]) -> None: ...
    @abstractmethod
    def set_pdf_path(self, inspection_id:int, pdf_path:str, status:int) -> None: ...
    @abstractmethod
    def get_inspection(self, inspection_id:int) -> Inspection: ...
    @abstractmethod
    def get_values(self, inspection_id:int) -> Dict[str,str]: ...
